// {keyword} = lowercase, {Keyword} = title-case
export const PATTERNS: string[] = [
  // Minimalist (15)
  "{keyword}",
  "{keyword}.",
  "{keyword} Co",
  "{keyword} & Co",
  "{Keyword}Studio",
  "{Keyword}Co",
  "{keyword} co.",
  "{Keyword}.",
  "{keyword} brand",
  "{Keyword}Brand",
  "{keyword} only",
  "{Keyword}Only",
  "{keyword} pure",
  "{Keyword}Pure",
  "{keyword} co",

  // Premium (14)
  "The {Keyword} Edit",
  "Maison {Keyword}",
  "{Keyword} Atelier",
  "{Keyword} House",
  "The {Keyword} House",
  "{Keyword} Reserve",
  "The {Keyword} Reserve",
  "{Keyword} Prestige",
  "{Keyword} Select",
  "The {Keyword} Collection",
  "{Keyword} & Craft",
  "The {Keyword} Studio",
  "The {Keyword} Workshop",
  "Bespoke {Keyword}",

  // Modern DTC (16)
  "{Keyword} Supply",
  "{Keyword} Collective",
  "Hello {keyword}",
  "{Keyword} Lab",
  "{Keyword} Works",
  "{Keyword} Co.",
  "{Keyword} Market",
  "{Keyword} Box",
  "{Keyword} Drop",
  "{Keyword} Club",
  "{Keyword} Society",
  "{Keyword} Guild",
  "{Keyword} Union",
  "{Keyword} Shop",
  "{Keyword} Store",
  "{Keyword} Depot",

  // Playful / Friendly (14)
  "Little {Keyword}",
  "Daily {Keyword}",
  "Honest {Keyword}",
  "Good {Keyword}",
  "Happy {Keyword}",
  "Simple {Keyword}",
  "Bright {Keyword}",
  "True {Keyword}",
  "Wild {Keyword}",
  "Fresh {Keyword}",
  "Clean {Keyword}",
  "Pure {Keyword}",
  "Kind {Keyword}",
  "Lucky {Keyword}",

  // Tech-y / Startup (14)
  "{keyword}.io",
  "{keyword}ly",
  "Get{Keyword}",
  "{Keyword} HQ",
  "{keyword}app",
  "{keyword}hub",
  "{keyword}base",
  "Try{Keyword}",
  "Use{Keyword}",
  "{Keyword} Platform",
  "{Keyword} OS",
  "{Keyword} Stack",
  "{Keyword} Cloud",
  "Meet{Keyword}",

  // Brandable suffix / prefix (15)
  "{Keyword}r",
  "{Keyword}ify",
  "{keyword}o",
  "{Keyword}ly",
  "{Keyword}ery",
  "{Keyword}ique",
  "{Keyword}able",
  "{Keyword}ful",
  "{Keyword}ish",
  "{Keyword}est",
  "{Keyword}wise",
  "{Keyword}craft",
  "{Keyword}forge",
  "{Keyword}ling",
  "{Keyword}ista",

  // Two-word with modifier (16)
  "{Keyword} Supply Co",
  "{Keyword} & Sons",
  "The {Keyword} Project",
  "{Keyword} & Co.",
  "The {Keyword} Collective",
  "{Keyword} & Partners",
  "The {Keyword} Agency",
  "{Keyword} & Associates",
  "{Keyword} Brothers",
  "{Keyword} Sisters",
  "{Keyword} & Friends",
  "The {Keyword} Brand",
  "{Keyword} By Design",
  "The {Keyword} Lab",
  "{Keyword} & Collective",
  "The {Keyword} Works",

  // Action / Verb-led (10)
  "Shop {Keyword}",
  "Love {Keyword}",
  "Live {Keyword}",
  "Make {Keyword}",
  "Craft {Keyword}",
  "Brew {Keyword}",
  "Grow {Keyword}",
  "Build {Keyword}",
  "Do {Keyword}",
  "Try {Keyword}",

  // Origin / Place-feel (8)
  "{Keyword} & Co",
  "{Keyword} & Craft",
  "{Keyword} Origins",
  "{Keyword} Co. Ltd",
  "{Keyword} Trading Co",
  "{Keyword} Merchants",
  "{Keyword} Exchange",
  "{Keyword} Quarter",

  // Essential / Basic (8)
  "{Keyword} Essentials",
  "Essential {Keyword}",
  "{Keyword} Basics",
  "Basic {Keyword}",
  "{Keyword} Standard",
  "Standard {Keyword}",
  "{Keyword} Core",
  "Core {Keyword}",
];
