import type { Metadata } from "next";
import Link from "next/link";
import MarketingNav from "@/components/MarketingNav";
import MarketingFooter from "@/components/MarketingFooter";
import CheckoutButton from "@/components/CheckoutButton";

export const metadata: Metadata = {
  title: "Pricing",
  description:
    "Start free for 7 days. Threely Pro: $12.99/month or $99.99/year. AI-generated daily tasks, personalized coaching insights, progress tracking, and mobile apps included.",
  alternates: { canonical: "/pricing" },
  openGraph: {
    title: "Threely Pricing — Free 7-Day Trial",
    description: "Start free for 7 days. Threely Pro: $12.99/month or $99.99/year with AI coaching, daily tasks, and progress tracking.",
  },
};

const FEATURES = [
  "Daily tasks generated by Threely Intelligence",
  "Personalized coaching insights after every review",
  "Up to 3 goals — focus drives progress",
  "Daily difficulty calibration based on your feedback",
  "Schedule-aware tasks (15 min to 2+ hours/day)",
  "Progress tracking and streaks",
  "iOS and Android apps",
  "Weekly summary reports",
];

export default function PricingPage() {
  return (
    <div style={{ fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif", color: "#e8e8e8", background: "#0a0a0a" }}>
      <MarketingNav />

      {/* Hero */}
      <section style={{
        background: "radial-gradient(ellipse at 50% 0%, rgba(99,91,255,0.08) 0%, transparent 60%)",
        padding: "4.5rem 1.5rem 3.5rem",
        textAlign: "center",
      }}>
        <div style={{ maxWidth: 600, margin: "0 auto" }}>
          <h1 style={{
            fontSize: "clamp(2rem, 5vw, 3rem)",
            fontWeight: 800,
            letterSpacing: "-0.04em",
            lineHeight: 1.1,
            marginBottom: "1rem",
          }}>
            Pricing
          </h1>
          <p style={{ fontSize: "1.05rem", color: "rgba(255,255,255,0.5)", lineHeight: 1.7 }}>
            Get Pro free for 7 days. Cancel anytime.
          </p>
        </div>
      </section>

      {/* Pricing cards — 2 tiers */}
      <section style={{ padding: "3.5rem 1.5rem", background: "#0a0a0a" }}>
        <div style={{
          maxWidth: 700,
          margin: "0 auto",
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
          gap: "1.5rem",
          alignItems: "start",
        }}>
          {/* Monthly */}
          <div style={{
            padding: "2rem 1.5rem",
            borderRadius: 16,
            border: "1px solid rgba(255,255,255,0.08)",
            background: "#0a0a0a",
          }}>
            <div style={{ fontSize: "0.72rem", fontWeight: 700, letterSpacing: "0.1em", color: "#635bff", textTransform: "uppercase", marginBottom: 8 }}>
              MONTHLY
            </div>
            <div style={{ display: "flex", alignItems: "baseline", gap: 4, marginBottom: 4 }}>
              <span style={{ fontSize: "2.5rem", fontWeight: 800, letterSpacing: "-0.03em" }}>$12.99</span>
              <span style={{ fontSize: "0.9rem", color: "#8898aa" }}>/month</span>
            </div>
            <p style={{ fontSize: "0.875rem", color: "rgba(255,255,255,0.5)", marginBottom: "1.5rem", lineHeight: 1.5 }}>
              Monthly access.<br />7 days free included.
            </p>
            <CheckoutButton plan="monthly" style={{
              display: "block",
              width: "100%",
              textAlign: "center",
              padding: "0.75rem 1.5rem",
              background: "#0a0a0a",
              color: "#635bff",
              border: "1.5px solid #635bff",
              borderRadius: 10,
              fontWeight: 700,
              fontSize: "0.95rem",
            }}>
              Get Pro Free
            </CheckoutButton>
          </div>

          {/* Yearly */}
          <div style={{
            padding: "2rem 1.5rem",
            borderRadius: 16,
            border: "2px solid #635bff",
            background: "#0a0a0a",
            position: "relative",
            boxShadow: "0 4px 20px rgba(99,91,255,0.12)",
          }}>
            <div style={{
              position: "absolute", top: -13, left: "50%", transform: "translateX(-50%)",
              background: "#635bff", color: "#fff",
              padding: "3px 14px", borderRadius: 20,
              fontSize: "0.7rem", fontWeight: 700, letterSpacing: "0.05em",
              whiteSpace: "nowrap",
            }}>
              SAVE 36%
            </div>
            <div style={{ fontSize: "0.72rem", fontWeight: 700, letterSpacing: "0.1em", color: "#635bff", textTransform: "uppercase", marginBottom: 8 }}>
              YEARLY — BEST VALUE
            </div>
            <div style={{ display: "flex", alignItems: "baseline", gap: 4, marginBottom: 4 }}>
              <span style={{ fontSize: "2.5rem", fontWeight: 800, letterSpacing: "-0.03em" }}>$99.99</span>
              <span style={{ fontSize: "0.9rem", color: "#8898aa" }}>/year</span>
            </div>
            <p style={{ fontSize: "0.875rem", color: "rgba(255,255,255,0.5)", marginBottom: "1.5rem", lineHeight: 1.5 }}>
              $8.33/month · billed annually.<br />7 days free included.
            </p>
            <CheckoutButton plan="yearly" style={{
              display: "block",
              width: "100%",
              textAlign: "center",
              padding: "0.75rem 1.5rem",
              background: "#635bff",
              color: "#fff",
              borderRadius: 10,
              fontWeight: 700,
              fontSize: "0.95rem",
              boxShadow: "0 4px 14px rgba(99,91,255,0.3)",
            }}>
              Get Pro Free
            </CheckoutButton>
          </div>
        </div>
      </section>

      {/* What's included */}
      <section style={{ padding: "3.5rem 1.5rem", background: "rgba(255,255,255,0.02)" }}>
        <div style={{ maxWidth: 600, margin: "0 auto" }}>
          <h2 style={{
            fontSize: "clamp(1.3rem, 3.5vw, 1.75rem)",
            fontWeight: 800,
            letterSpacing: "-0.03em",
            textAlign: "center",
            marginBottom: "2rem",
          }}>
            Everything included in every plan
          </h2>
          <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
            {FEATURES.map(f => (
              <div key={f} style={{ display: "flex", alignItems: "center", gap: 12 }}>
                <div style={{
                  width: 24, height: 24, borderRadius: "50%",
                  background: "#ede9ff", color: "#635bff",
                  display: "flex", alignItems: "center", justifyContent: "center",
                  fontSize: 14, fontWeight: 700, flexShrink: 0,
                }}>
                  ✓
                </div>
                <span style={{ fontSize: "0.95rem", color: "#e8e8e8" }}>{f}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Billing FAQ */}
      <section style={{ padding: "3.5rem 1.5rem", background: "#0a0a0a" }}>
        <div style={{ maxWidth: 600, margin: "0 auto" }}>
          <h2 style={{
            fontSize: "clamp(1.3rem, 3.5vw, 1.75rem)",
            fontWeight: 800,
            letterSpacing: "-0.03em",
            textAlign: "center",
            marginBottom: "2rem",
          }}>
            Billing questions
          </h2>
          <div style={{ display: "flex", flexDirection: "column", gap: "1.25rem" }}>
            {[
              { q: "Do I need a credit card to start?", a: "Yes — we securely collect payment details when you sign up, but you won't be charged during the 7-day free period. We'll send you a reminder 2 days before it ends so there are no surprises. You can cancel anytime." },
              { q: "Can I cancel anytime?", a: "Yes. Cancel your subscription at any time from your profile settings. You'll keep access until the end of your current billing period." },
              { q: "What happens after my 7 free days?", a: "You'll be prompted to choose a plan. If you don't subscribe, your account stays active — you just won't receive new AI-generated tasks until you upgrade." },
              { q: "Is there a refund policy?", a: "Yes! We offer a 7-day, no-questions-asked refund policy. If you're not satisfied within 7 days of your first charge, just email refund@threely.co and we'll refund you in full.", link: "/refund", linkText: "View Refund Policy" },
            ].map(item => (
              <div key={item.q} style={{
                background: "rgba(255,255,255,0.02)",
                borderRadius: 14,
                padding: "1.25rem 1.5rem",
                border: "1px solid rgba(255,255,255,0.08)",
              }}>
                <h3 style={{ fontSize: "1rem", fontWeight: 700, marginBottom: 8 }}>{item.q}</h3>
                <p style={{ fontSize: "0.9rem", color: "rgba(255,255,255,0.5)", lineHeight: 1.7 }}>{item.a}</p>
                {"link" in item && item.link && (
                  <Link href={item.link} style={{
                    display: "inline-block",
                    marginTop: 12,
                    padding: "0.5rem 1.15rem",
                    background: "#635bff",
                    color: "#fff",
                    borderRadius: 8,
                    fontSize: "0.85rem",
                    fontWeight: 600,
                    textDecoration: "none",
                  }}>
                    {item.linkText} →
                  </Link>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section style={{
        padding: "4rem 1.5rem",
        background: "#0a0a0a", borderTop: "1px solid rgba(255,255,255,0.06)",
        textAlign: "center",
        color: "#fff",
      }}>
        <div style={{ maxWidth: 500, margin: "0 auto" }}>
          <h2 style={{ fontSize: "clamp(1.4rem, 4vw, 2rem)", fontWeight: 800, letterSpacing: "-0.03em", marginBottom: "0.75rem" }}>
            Get Pro free for 7 days
          </h2>
          <p style={{ fontSize: "1rem", color: "rgba(255,255,255,0.8)", marginBottom: "1.5rem" }}>
            Set your first goal and get personalized tasks in under a minute.
          </p>
          <Link href="/welcome" style={{
            display: "inline-block",
            padding: "0.875rem 2.5rem",
            background: "#635bff",
            color: "#fff",
            fontWeight: 700,
            fontSize: "1rem",
            borderRadius: 10,
            textDecoration: "none",
            boxShadow: "0 4px 14px rgba(0,0,0,0.15)",
          }}>
            Create free account →
          </Link>
        </div>
      </section>

      <MarketingFooter />
    </div>
  );
}
